const ReportService = require('../services/reportService');
const TimeLog = require('../models/TimeLog');
const ExpenseLog = require('../models/ExpenseLog');
const ClientProject = require('../models/ClientProject');
const { ERROR_CODES } = require('../utils/constants');
const { t } = require('../utils/i18n');
const { getYearBounds, getMonthBounds } = require('../utils/timezone');

// 从已加载的 req.user 上取时区；非法或缺失时回退到默认，避免报表崩溃。
// 注意：报表正确性依赖此时区——跨时区用户的工时/开支必须按本地月份/年份归类，
// 否则税务数据会出错（例如美东 1/31 23:00 工作到 2/1 00:00，UTC 落在 2 月，但应归 1 月）。
const resolveTimezone = (req) => {
  const tz = req?.user?.timezone;
  return tz && typeof tz === 'string' ? tz : 'America/New_York';
};

// 报表默认年/月必须按用户时区计算：UTC+13 用户在本地 12/31 23:30 请求时，
// UTC 已是次年 1 月，服务器时钟会给出错误的默认月份。
const nowInTz = (timezone) => require('luxon').DateTime.now().setZone(timezone);

const getMonthly = async (req, res, next) => {
  try {
    const { year, month, projectId } = req.query;
    const timezone = resolveTimezone(req);
    const nowTz = nowInTz(timezone);
    const yearNum = year == null ? nowTz.year : Number.parseInt(year, 10);
    const monthNum = month == null ? nowTz.month : Number.parseInt(month, 10);
    if (!Number.isInteger(yearNum) || yearNum < 2000 || yearNum > 2100 ||
        !Number.isInteger(monthNum) || monthNum < 1 || monthNum > 12) {
      return res.status(400).json({
        code: ERROR_CODES.BAD_REQUEST,
        msg: t('errors.report.yearMonthInvalid', req.lang),
        data: null,
        timestamp: Date.now(),
      });
    }

    const report = await ReportService.getMonthlyReport(req.userId, yearNum, monthNum, projectId, timezone);

    return res.status(200).json({
      code: ERROR_CODES.SUCCESS,
      msg: t('common.success', req.lang),
      data: report,
      timestamp: Date.now(),
    });
  } catch (error) {
    next(error);
  }
};

const getAnnual = async (req, res, next) => {
  try {
    const { year } = req.query;
    const timezone = resolveTimezone(req);
    const yearNum = year == null ? nowInTz(timezone).year : Number.parseInt(year, 10);
    if (!Number.isInteger(yearNum) || yearNum < 2000 || yearNum > 2100) {
      return res.status(400).json({ code: ERROR_CODES.BAD_REQUEST, msg: t('errors.report.yearInvalid', req.lang), data: null, timestamp: Date.now() });
    }

    const report = await ReportService.getAnnualReport(req.userId, yearNum, timezone);

    return res.status(200).json({
      code: ERROR_CODES.SUCCESS,
      msg: t('common.success', req.lang),
      data: report,
      timestamp: Date.now(),
    });
  } catch (error) {
    next(error);
  }
};

const exportPdf = async (req, res, next) => {
  try {
    const { type, year, month } = req.query;
    const PDFDocument = require('pdfkit');

    const buildPdf = (report, title, filename) => new Promise((resolve, reject) => {
      try {
        const chunks = [];
        const doc = new PDFDocument();
        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('error', reject);
        doc.on('end', () => resolve(Buffer.concat(chunks)));

        doc.fontSize(20).text(title, { align: 'center' });
        doc.moveDown();
        doc.fontSize(14).text(`Period: ${report.period || report.year}`);
        doc.moveDown();
        doc.fontSize(12).text(`Total Billable Hours: ${report.totalBillableHours}h`);
        doc.text(`Total Billable Amount: $${report.totalBillableAmount.toFixed(2)}`);
        doc.text(`Total Expenses: $${report.totalExpenses.toFixed(2)}`);
        doc.text(`Tax Deductible Expenses: $${report.taxDeductibleExpenses.toFixed(2)}`);
        doc.text(`Net Income: $${report.netIncome.toFixed(2)}`);
        if (report.estimatedSelfEmploymentTax !== undefined) {
          doc.text(`Estimated Self-Employment Tax: $${report.estimatedSelfEmploymentTax.toFixed(2)}`);
          doc.moveDown();
          doc.fontSize(10).fillColor('red').text('DISCLAIMER: This report is for record-keeping purposes only and does not constitute tax advice.', { align: 'center' });
          doc.text('Please consult a certified tax professional for filing advice.', { align: 'center' });
        } else {
          doc.moveDown();
          doc.fontSize(10).text('Generated by Freelance Hub. For record-keeping purposes only.', { align: 'center' });
        }
        doc.end();
      } catch (err) {
        reject(err);
      }
    });

    if (type === 'monthly') {
      const yearNum = year == null ? new Date().getFullYear() : Number.parseInt(year, 10);
      const monthNum = month == null ? new Date().getMonth() + 1 : Number.parseInt(month, 10);
      if (!Number.isInteger(yearNum) || yearNum < 2000 || yearNum > 2100 || !Number.isInteger(monthNum) || monthNum < 1 || monthNum > 12) {
        return res.status(400).json({ code: ERROR_CODES.BAD_REQUEST, msg: t('errors.report.yearMonthRequired', req.lang), data: null, timestamp: Date.now() });
      }
      const timezone = resolveTimezone(req);
      const report = await ReportService.getMonthlyReport(req.userId, yearNum, monthNum, null, timezone);

      const pdfBuffer = await buildPdf(report, 'Freelance Hub Monthly Report', `monthly_report_${yearNum}_${monthNum}.pdf`);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="monthly_report_${yearNum}_${monthNum}.pdf"`);
      return res.send(pdfBuffer);
    }

    if (type === 'annual') {
      const yearNum = year == null ? new Date().getFullYear() : Number.parseInt(year, 10);
      if (!Number.isInteger(yearNum) || yearNum < 2000 || yearNum > 2100) {
        return res.status(400).json({ code: ERROR_CODES.BAD_REQUEST, msg: t('errors.report.yearRequired', req.lang), data: null, timestamp: Date.now() });
      }
      const timezone = resolveTimezone(req);
      const report = await ReportService.getAnnualReport(req.userId, yearNum, timezone);

      const pdfBuffer = await buildPdf(report, 'Freelance Hub Annual Tax Summary', `annual_tax_summary_${yearNum}.pdf`);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="annual_tax_summary_${yearNum}.pdf"`);
      return res.send(pdfBuffer);
    }

    return res.status(400).json({
      code: ERROR_CODES.BAD_REQUEST,
      msg: t('errors.report.exportTypeInvalid', req.lang),
      data: null,
      timestamp: Date.now(),
    });
  } catch (error) {
    next(error);
  }
};

// 各实体导出到 CSV（RFC 4180 转义）。Web 后台 Annual 专属批量导出。
const toCsv = (rows) => {
  const escape = (v) => {
    if (v === null || v === undefined) return '';
    let s = String(v);
    // 公式注入防护：以 = + - @ 开头的单元格在 Excel 中会被解释为公式，
    // 商家名/备注/标签等用户可控字段必须加前缀破坏公式语义。
    if (/^[=+\-@\t\r]/.test(s)) s = `'${s}`;
    return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  return rows.map((r) => r.map(escape).join(',')).join('\r\n') + '\r\n';
};

const exportCsv = async (req, res, next) => {
  try {
    const { year } = req.query;
    const yearNum = year == null ? new Date().getFullYear() : Number.parseInt(year, 10);
    if (!Number.isInteger(yearNum) || yearNum < 2000 || yearNum > 2100) {
      return res.status(400).json({ code: ERROR_CODES.BAD_REQUEST, msg: t('errors.report.yearRequired', req.lang), data: null, timestamp: Date.now() });
    }

    // 按用户时区计算年界，避免跨年工时/开支因 UTC 偏移被归错年度（税务导出必须准确）。
    const timezone = resolveTimezone(req);
    const { start: startDate, end: endDate } = getYearBounds(yearNum, timezone);
    const [projects, timeLogs, expenses] = await Promise.all([
      ClientProject.find({ userId: req.userId, isDeleted: false }),
      TimeLog.find({ userId: req.userId, isDeleted: false, startTime: { $gte: startDate, $lt: endDate } }),
      ExpenseLog.find({ userId: req.userId, isDeleted: false, expenseDate: { $gte: startDate, $lt: endDate } }),
    ]);
    const projectName = {};
    projects.forEach((p) => { projectName[p.projectId] = p.projectName; });

    const timeCsv = toCsv([
      ['Time logs'],
      ['TimeLogId', 'Project', 'StartTime', 'EndTime', 'Duration(h)', 'Billable', 'BillableAmount', 'Tag', 'Note'],
      ...timeLogs.map((t) => [
        t.timeLogId, projectName[t.projectId] || t.projectId, new Date(t.startTime).toISOString(),
        t.endTime ? new Date(t.endTime).toISOString() : '', t.duration, t.isBillable ? 'Yes' : 'No',
        t.billableAmount, t.tag, t.note,
      ]),
    ]);

    const expenseCsv = toCsv([
      ['Expenses'],
      ['ExpenseId', 'Project', 'Amount', 'Currency', 'Date', 'Category', 'TaxDeductible', 'Merchant', 'Note'],
      ...expenses.map((e) => [
        e.expenseId, projectName[e.projectId] || '', e.amount, e.currency,
        new Date(e.expenseDate).toISOString(), e.category, e.isTaxDeductible ? 'Yes' : 'No', e.merchant, e.note,
      ]),
    ]);

    const csv = `\uFEFF${timeCsv}\n${expenseCsv}`;
    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="freelance_hub_${yearNum}_export.csv"`);
    return res.send(csv);
  } catch (error) {
    next(error);
  }
};

module.exports = { getMonthly, getAnnual, exportPdf, exportCsv };
