const ERROR_CODES = {
  SUCCESS: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMIT: 429,
  INTERNAL_ERROR: 500,
  REFRESH_TOKEN_EXPIRED: 1001,
  FREE_PROJECT_LIMIT: 2001,
  NEED_MONTHLY: 2002,
  NEED_ANNUAL: 2003,
  SYNC_CONFLICT: 3001,
};

const PREMIUM_TYPES = {
  FREE: 'free',
  MONTHLY: 'monthly',
  ANNUAL: 'annual',
};

const FREE_PROJECT_LIMIT = 3;

module.exports = { ERROR_CODES, PREMIUM_TYPES, FREE_PROJECT_LIMIT };
