import 'package:flutter/material.dart';
import '../config/app_theme.dart';

/// Lightweight in-app viewer for legal/help documents (demo-grade placeholders).
///
/// Shows Privacy Policy (§7.3 — 10 required sections), Terms of Service,
/// or Help & Support contact info without opening an external browser.
class LegalDocViewer extends StatelessWidget {
  final LegalDocType docType;

  const LegalDocViewer({super.key, required this.docType});

  static String titleFor(LegalDocType type) {
    switch (type) {
      case LegalDocType.privacyPolicy:
        return 'Privacy Policy';
      case LegalDocType.termsOfService:
        return 'Terms of Service';
      case LegalDocType.helpSupport:
        return 'Help & Support';
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(titleFor(docType))),
      body: docType == LegalDocType.helpSupport
          ? _buildHelp(context)
          : ListView(
              padding: const EdgeInsets.all(16),
              children: docType == LegalDocType.privacyPolicy
                  ? _privacySections()
                  : _termsSections(),
            ),
    );
  }

  // ── Help & Support ──────────────────────────────────────────
  Widget _buildHelp(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Icon(Icons.support_agent, size: 64, color: AppTheme.primary),
          const SizedBox(height: 16),
          const Text('Need a hand?', style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold)),
          const SizedBox(height: 8),
          const Text(
            'We typically respond within 24 hours on business days.',
            style: TextStyle(color: AppTheme.textSecondary),
          ),
          const SizedBox(height: 24),
          _contactRow(Icons.email_outlined, 'Email', 'support@freelancehub.app'),
          const SizedBox(height: 12),
          _contactRow(Icons.access_time, 'Hours', 'Mon–Fri, 9 AM – 5 PM (UTC)'),
          const SizedBox(height: 32),
          const Text(
            'Frequently Asked Questions',
            style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 8),
          _faqItem('How do I export my data?',
              'Go to Settings → Data Management → Export Data to download a JSON file.'),
          _faqItem('Can I cancel my subscription?',
              'Yes — manage your subscription anytime in Settings → Subscription.'),
          _faqItem('Is my data backed up?',
              'Cloud Sync is available with the Annual (Contractor) plan.'),
        ],
      ),
    );
  }

  Widget _contactRow(IconData icon, String label, String value) {
    return Row(
      children: [
        Icon(icon, size: 20, color: AppTheme.textSecondary),
        const SizedBox(width: 12),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(label, style: const TextStyle(fontSize: 12, color: AppTheme.textSecondary)),
              Text(value, style: const TextStyle(fontSize: 15)),
            ],
          ),
        ),
      ],
    );
  }

  Widget _faqItem(String q, String a) {
    return ExpansionTile(
      tilePadding: EdgeInsets.zero,
      title: Text(q, style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w500)),
      children: [
        Align(
          alignment: Alignment.centerLeft,
          child: Padding(
            padding: const EdgeInsets.only(bottom: 8),
            child: Text(a, style: const TextStyle(fontSize: 13, color: AppTheme.textSecondary)),
          ),
        ),
      ],
    );
  }

  // ── Privacy Policy (§7.3 — 10 sections) ─────────────────────
  List<Widget> _privacySections() {
    return [
      _section('1. Information We Collect',
          'We collect information you provide directly (name, email address) and data generated by your use of the app (projects, time logs, expenses).'),
      _section('2. How We Use Your Information',
          'We use your data to provide and improve the Service, process payments, send subscription reminders, and provide customer support.'),
      _section('3. Legal Basis for Processing',
          'Under GDPR, we process your data based on your consent, contract performance, and our legitimate business interests.'),
      _section('4. Data Sharing and Disclosure',
          'We do not sell your data. We share it only with service providers (hosting, payments) under strict confidentiality, or when required by law.'),
      _section('5. Data Retention',
          'We retain your data for as long as your account is active. Deleted accounts enter a 30-day grace period, after which all data is permanently erased.'),
      _section('6. Data Security',
          'We use industry-standard encryption (TLS in transit, AES-256 at rest) and regular security audits to protect your data.'),
      _section('7. Your GDPR Rights',
          'You have the right to access, rectify, erase, restrict, port, and object to the processing of your personal data. To exercise these rights, contact support@freelancehub.app.'),
      _section('8. International Data Transfers',
          'Your data may be transferred to countries outside the EEA. We ensure appropriate safeguards (SCCs) are in place for such transfers.'),
      _section('9. Children\u2019s Privacy',
          'The Service is not directed to individuals under 16. We do not knowingly collect data from children.'),
      _section('10. Changes to This Policy',
          'We may update this policy from time to time. We will notify you of material changes via the app or email at least 30 days in advance.'),
      const SizedBox(height: 16),
      const Text(
        'Last updated: August 2026\nThis is demo placeholder text and is not legal advice.',
        style: TextStyle(fontSize: 12, color: AppTheme.textDisabled),
      ),
    ];
  }

  // ── Terms of Service ────────────────────────────────────────
  List<Widget> _termsSections() {
    return [
      _section('1. Acceptance of Terms',
          'By accessing or using Freelance Hub, you agree to be bound by these Terms of Service. If you do not agree, please discontinue use.'),
      _section('2. Description of Service',
          'Freelance Hub provides time tracking, expense management, and reporting tools for freelance professionals. Some features require a paid subscription.'),
      _section('3. User Accounts',
          'You are responsible for maintaining the security of your account and password. You must provide accurate and complete information when registering.'),
      _section('4. Acceptable Use',
          'You agree not to misuse the Service, upload malicious content, attempt unauthorized access, or use the Service for any illegal purpose.'),
      _section('5. Subscriptions and Billing',
          'Paid subscriptions auto-renew unless canceled at least 24 hours before the renewal date. Fees are non-refundable except where required by law.'),
      _section('6. Intellectual Property',
          'The Service and its content are owned by Freelance Hub. You retain ownership of all data you submit through the Service.'),
      _section('7. Termination',
          'You may delete your account at any time. We may suspend or terminate access for violations of these Terms.'),
      _section('8. Limitation of Liability',
          'The Service is provided "as is" without warranties. Freelance Hub shall not be liable for indirect, incidental, or consequential damages.'),
      _section('9. Governing Law',
          'These Terms are governed by the laws of the jurisdiction in which the Service provider is established, without regard to conflict of law principles.'),
      _section('10. Contact',
          'For questions about these Terms, please contact support@freelancehub.app.'),
      const SizedBox(height: 16),
      const Text(
        'Last updated: August 2026\nThis is demo placeholder text and is not legal advice.',
        style: TextStyle(fontSize: 12, color: AppTheme.textDisabled),
      ),
    ];
  }

  Widget _section(String title, String body) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: const TextStyle(fontSize: 15, fontWeight: FontWeight.bold)),
          const SizedBox(height: 4),
          Text(body, style: const TextStyle(fontSize: 14, color: AppTheme.textSecondary, height: 1.5)),
        ],
      ),
    );
  }
}

enum LegalDocType { privacyPolicy, termsOfService, helpSupport }